### ISSUE TITLE
v3.4.0-beta.1 output does not match actual output

### ISSUE THREAD

**Issue by jacobq** [ember-cli/ember-new-output#7]
Reproduction steps:

* `npm install -g ember-cli@3.4.0-beta.1`
* `ember new foo`
* `grep ember-source package.json` # Observe `~3.2.0-beta.2` instead of [`~3.4.0-beta.1`](https://github.com/ember-cli/ember-new-output/blob/master/package.json#L39) -- `ember-data` also

I think this might be an `npm` / release problem since [`ember-cli/blueprints/app/files/package.json`](https://github.com/ember-cli/ember-cli/blob/v3.4.0-beta.1/blueprints/app/files/package.json#L40) matches [`ember-new-output/package.json`](https://github.com/ember-cli/ember-new-output/blob/v3.4.0-beta.1/package.json#L39), but downloading the [tar ball from npm](https://registry.npmjs.org/ember-cli/-/ember-cli-3.4.0-beta.1.tgz) shows:

```
$ wget https://registry.npmjs.org/ember-cli/-/ember-cli-3.4.0-beta.1.tgz
$ tar zxf ember-cli-3.4.0-beta.1.tgz
$ grep ember-source package/blueprints/app/files/package.json 
    "ember-source": "~3.2.0-beta.2<% if (welcome) { %>",

```

**Comment by kellyselden** [comment]
Must have been a bad beta release, but this repo is unaffected. Thanks.
